import { awsSchema } from '../../schemas/aws/variables';
import { serializeValue } from './tfvars-serializer';
import type { FormValues, DeploymentMode, SchemaVariable } from '../../schemas/types';

// ─── AWS tfvars generator ──────────────────────────────────────────────────
// Produces a terraform.tfvars string matching the layout of
// terraform-databricks-sra/aws/tf/template.tfvars.example

/**
 * Look up a schema variable definition by name.
 */
function findVar(name: string): SchemaVariable | undefined {
  return awsSchema.variables.find((v) => v.name === name);
}

/**
 * Render a single variable assignment line.
 *
 * - Empty required fields get a placeholder comment
 * - Null/undefined optional fields get commented out
 * - Everything else is serialized normally
 */
function renderVar(
  name: string,
  value: unknown,
  commentOut: boolean = false,
): string {
  const varDef = findVar(name);
  if (!varDef) return '';

  // Required field with no value — show empty string with reminder
  if (
    varDef.required &&
    varDef.terraformType === 'string' &&
    (value === undefined || value === null || value === '')
  ) {
    return `${name} = ""  # Required — fill in before running terraform`;
  }

  // Optional field with no value -- comment it out
  if (commentOut && (value === undefined || value === null || value === '')) {
    return `# ${name} = ""`;
  }

  const serialized = serializeValue(value, varDef.terraformType);
  return `${name} = ${serialized}`;
}

/**
 * Generate terraform.tfvars content for an AWS SRA deployment.
 */
export function generateAwsTfvars(values: FormValues, mode: DeploymentMode): string {
  const merged: FormValues = { ...values, ...mode.fixedValues };
  const v = (name: string): unknown => merged[name];
  const isIsolated = merged.network_configuration === 'isolated';

  const lines: string[] = [];

  // ── Header ─────────────────────────────────────────────────────────────────
  lines.push('# =============================================================================');
  lines.push('# Configuration Variables for AWS and Databricks');
  lines.push(`# Generated by Databricks SRA WebUI on ${new Date().toISOString()}`);
  lines.push('# =============================================================================');
  lines.push('');

  // ── AWS Variables ──────────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# AWS Variables');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');
  lines.push('# AWS account ID where resources will be deployed');
  lines.push(renderVar('aws_account_id', v('aws_account_id')));
  lines.push('');
  lines.push('# AWS region for deployment');
  lines.push(renderVar('region', v('region')));
  lines.push('');

  // ── Databricks Variables ───────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Databricks Variables');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');
  lines.push('# Admin user email for workspace and catalog management');
  lines.push(renderVar('admin_user', v('admin_user')));
  lines.push('');
  lines.push('# Databricks account ID');
  lines.push(renderVar('databricks_account_id', v('databricks_account_id')));
  lines.push('');

  // ── Resource Configuration ─────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Resource Configuration');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');
  lines.push('# Prefix used for naming and tagging resources (e.g., S3 buckets, IAM roles)');
  lines.push(renderVar('resource_prefix', v('resource_prefix')));
  lines.push('');

  // ── Network Configuration ──────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Network Configuration');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');
  lines.push('# Network type: "custom" or "isolated" (see README.md for more information)');
  lines.push(renderVar('network_configuration', v('network_configuration')));
  lines.push('');

  if (isIsolated) {
    lines.push('# ISOLATED NETWORK CONFIGURATION');
    lines.push('# Required when using network_configuration = "isolated"');

    // Aligned to match SRA template formatting
    const vpcCidr = serializeValue(v('vpc_cidr_range'), 'string');
    const privateCidr = serializeValue(v('private_subnets_cidr'), 'list(string)');
    const plCidr = serializeValue(v('privatelink_subnets_cidr'), 'list(string)');
    lines.push(`vpc_cidr_range           = ${vpcCidr}`);
    lines.push(`private_subnets_cidr     = ${privateCidr}`);
    lines.push(`privatelink_subnets_cidr = ${plCidr}`);

    // sg_egress_ports: output as bare numbers to match template (Terraform auto-converts to strings)
    const ports = v('sg_egress_ports');
    if (Array.isArray(ports) && ports.length > 0) {
      const numPorts = ports.map((p: unknown) => String(p).replace(/"/g, ''));
      lines.push(`sg_egress_ports          = [${numPorts.join(', ')}]`);
    } else {
      lines.push(renderVar('sg_egress_ports', ports));
    }
    lines.push('');
    lines.push('# CUSTOM NETWORK CONFIGURATION');
    lines.push('# Uncomment and configure the following variables for custom networking:');
    lines.push('# Required when using network_configure = "custom"');
    lines.push(
      '# Ensure that an STS interface endpoint, a Kinesis endpoint, and an S3 gateway endpoint are available within the VPC and associated with private subnet route tables.',
    );
    lines.push(
      '# Ensure that Private DNS names have been enabled for Databricks PrivateLink endpoints.',
    );
    lines.push('');
    lines.push('# custom_vpc_id             = ""');
    lines.push('# custom_private_subnet_ids = ["", ""]');
    lines.push('# custom_sg_id              = ""');
    lines.push('# custom_relay_vpce_id      = ""');
    lines.push('# custom_workspace_vpce_id  = ""');
  } else {
    lines.push('# ISOLATED NETWORK CONFIGURATION');
    lines.push('# Uncomment and configure the following variables for isolated networking:');
    lines.push('');
    lines.push('# vpc_cidr_range           = "10.0.0.0/18"');
    lines.push('# private_subnets_cidr     = ["10.0.0.0/22", "10.0.4.0/22", "10.0.8.0/22"]');
    lines.push(
      '# privatelink_subnets_cidr = ["10.0.28.0/26", "10.0.28.64/26", "10.0.28.128/26"]',
    );
    lines.push(
      '# sg_egress_ports          = [443, 2443, 5432, 6666, 8443, 8444, 8445, 8446, 8447, 8448, 8449, 8450, 8451]',
    );
    lines.push('');
    lines.push('# CUSTOM NETWORK CONFIGURATION');
    lines.push('# Required when using network_configuration = "custom"');
    lines.push(
      '# Ensure that an STS interface endpoint, a Kinesis endpoint, and an S3 gateway endpoint are available within the VPC and associated with private subnet route tables.',
    );
    lines.push(
      '# Ensure that Private DNS names have been enabled for Databricks PrivateLink endpoints.',
    );
    lines.push('');
    lines.push(renderVar('custom_vpc_id', v('custom_vpc_id')));
    lines.push(renderVar('custom_private_subnet_ids', v('custom_private_subnet_ids')));
    lines.push(renderVar('custom_sg_id', v('custom_sg_id')));
    lines.push(renderVar('custom_relay_vpce_id', v('custom_relay_vpce_id')));
    lines.push(renderVar('custom_workspace_vpce_id', v('custom_workspace_vpce_id')));
  }
  lines.push('');

  // ── Feature Flags ──────────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Feature Flags');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  // metastore_exists — required (no default), always output
  lines.push(renderVar('metastore_exists', v('metastore_exists') ?? false));

  // audit_log_delivery_exists — default: false. Only output if true.
  if (v('audit_log_delivery_exists') === true) {
    lines.push(renderVar('audit_log_delivery_exists', true));
  }

  // enable_security_analysis_tool — default: false. Only output if true.
  if (v('enable_security_analysis_tool') === true) {
    lines.push(renderVar('enable_security_analysis_tool', true));
  }

  // enable_compliance_security_profile — default: false. Only output if true.
  if (v('enable_compliance_security_profile') === true) {
    lines.push(renderVar('enable_compliance_security_profile', true));
  }

  // compliance_standards — required (no default), nullable. Always output.
  const complianceVal = v('compliance_standards');
  if (Array.isArray(complianceVal) && complianceVal.length > 0) {
    lines.push(renderVar('compliance_standards', complianceVal));
  } else {
    lines.push('compliance_standards = null');
  }
  lines.push('');

  // ── Optional Configuration ─────────────────────────────────────────────────
  // Only output variables where the user set a non-default value.
  // Omitted variables use the Terraform module defaults.

  const optionalLines: string[] = [];

  const cmkVal = v('cmk_admin_arn');
  if (cmkVal && cmkVal !== '') {
    optionalLines.push('# CMK Admin ARN (required for non-root account CMK usage)');
    optionalLines.push(renderVar('cmk_admin_arn', cmkVal));
  }

  const deployNameVal = v('deployment_name');
  if (deployNameVal && deployNameVal !== '') {
    optionalLines.push('# Deployment name for the workspace (must be enabled by Databricks representative)');
    optionalLines.push(renderVar('deployment_name', deployNameVal));
  }

  const govShardVal = v('databricks_gov_shard');
  if (govShardVal && govShardVal !== '') {
    optionalLines.push('# GovCloud shard: "civilian" or "dod"');
    optionalLines.push(renderVar('databricks_gov_shard', govShardVal));
  }

  if (optionalLines.length > 0) {
    lines.push('# -----------------------------------------------------------------------------');
    lines.push('# Optional Configuration');
    lines.push('# -----------------------------------------------------------------------------');
    lines.push('');
    lines.push(...optionalLines);
  }

  return lines.join('\n') + '\n';
}
