import { azureSchema } from '../../schemas/azure/variables';
import { serializeValue } from './tfvars-serializer';
import type { FormValues, DeploymentMode, SchemaVariable } from '../../schemas/types';

// ─── Azure tfvars generator ──────────────────────────────────────────────────
// Produces a terraform.tfvars string matching the layout of
// terraform-databricks-sra/azure/tf/template*.example.tfvars

/**
 * Look up a schema variable definition by name.
 */
function findVar(name: string): SchemaVariable | undefined {
  return azureSchema.variables.find((v) => v.name === name);
}

/**
 * Render a single variable assignment line.
 *
 * - Sensitive fields that are empty/undefined get a TF_VAR hint.
 * - Null/undefined optional fields get commented out.
 * - Everything else is serialized normally.
 */
function renderVar(
  name: string,
  value: unknown,
  commentOut: boolean = false,
): string {
  const varDef = findVar(name);
  if (!varDef) return '';

  // Required field with no value — show empty string with reminder
  if (
    varDef.required &&
    varDef.terraformType === 'string' &&
    (value === undefined || value === null || value === '')
  ) {
    return `${name} = ""  # Required — fill in before running terraform`;
  }

  // Optional field with no value -- comment it out
  if (commentOut && (value === undefined || value === null || value === '')) {
    return `# ${name} = ""`;
  }

  const serialized = serializeValue(value, varDef.terraformType);
  return `${name} = ${serialized}`;
}

/**
 * Render a variable that is not in the schema (e.g. fixed values like create_hub).
 */
function renderFixedVar(name: string, value: unknown): string {
  if (typeof value === 'boolean') {
    return `${name} = ${value ? 'true' : 'false'}`;
  }
  if (typeof value === 'string') {
    return `${name} = "${value}"`;
  }
  return `${name} = ${String(value)}`;
}

/**
 * Check if a value is "empty" (null, undefined, empty string, empty array, empty object).
 */
function isEmpty(value: unknown): boolean {
  if (value === undefined || value === null || value === '') return true;
  if (Array.isArray(value) && value.length === 0) return true;
  if (typeof value === 'object' && !Array.isArray(value) && Object.keys(value as object).length === 0)
    return true;
  return false;
}

/**
 * Generate terraform.tfvars content for an Azure SRA deployment.
 */
export function generateAzureTfvars(values: FormValues, mode: DeploymentMode): string {
  const merged: FormValues = { ...values, ...mode.fixedValues };
  const v = (name: string): unknown => merged[name];

  const isFullSra = mode.id === 'full-sra';
  const isByoSpoke = mode.id === 'byo-spoke';

  const lines: string[] = [];

  // ── Header ─────────────────────────────────────────────────────────────────
  lines.push('# =============================================================================');
  lines.push('# Configuration Variables for Azure Databricks SRA');
  lines.push(`# Generated by Databricks SRA WebUI on ${new Date().toISOString()}`);
  lines.push(`# Mode: ${mode.label}`);
  lines.push('# =============================================================================');
  lines.push('');

  // ── Account & Identity ────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Account & Identity');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');
  lines.push(renderVar('databricks_account_id', v('databricks_account_id')));
  lines.push(renderVar('subscription_id', v('subscription_id')));
  lines.push(renderVar('location', v('location')));
  lines.push(renderVar('resource_suffix', v('resource_suffix')));
  lines.push('');

  // ── Hub Configuration ─────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Hub Configuration');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  if (isFullSra) {
    // Full SRA: create_hub defaults to true, no need to emit it explicitly
    // (it matches the Terraform default)
    lines.push(renderVar('hub_resource_suffix', v('hub_resource_suffix')));
    lines.push(renderVar('hub_vnet_cidr', v('hub_vnet_cidr')));
  } else {
    // BYO Hub or BYO Spoke: create_hub = false
    lines.push(renderFixedVar('create_hub', false));
    lines.push('');

    // Metastore ID required when create_hub is false
    lines.push(renderVar('databricks_metastore_id', v('databricks_metastore_id')));
    lines.push('');

    // Existing hub VNet details
    const existingHubVnet = v('existing_hub_vnet');
    if (!isEmpty(existingHubVnet)) {
      lines.push(renderVar('existing_hub_vnet', existingHubVnet));
    } else {
      lines.push('# existing_hub_vnet = {');
      lines.push('#   route_table_id = "/subscriptions/.../routeTables/..."');
      lines.push('#   vnet_id        = "/subscriptions/.../virtualNetworks/..."');
      lines.push('# }');
    }
    lines.push('');

    // NCC and network policy
    lines.push('# Network Connectivity Configuration');
    const nccId = v('existing_ncc_id');
    if (!isEmpty(nccId)) {
      lines.push(renderVar('existing_ncc_id', nccId));
    } else {
      lines.push('# existing_ncc_id = ""');
    }

    const nccName = v('existing_ncc_name');
    if (!isEmpty(nccName)) {
      lines.push(renderVar('existing_ncc_name', nccName));
    } else {
      lines.push('# existing_ncc_name = ""');
    }

    const networkPolicyId = v('existing_network_policy_id');
    if (!isEmpty(networkPolicyId)) {
      lines.push(renderVar('existing_network_policy_id', networkPolicyId));
    } else {
      lines.push('# existing_network_policy_id = ""');
    }
  }
  lines.push('');

  // ── Workspace Network ─────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Workspace Network');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  if (isByoSpoke) {
    lines.push(renderFixedVar('create_workspace_vnet', false));
    lines.push('');

    // BYO Spoke: existing_workspace_vnet is required
    const existingWsVnet = v('existing_workspace_vnet');
    if (!isEmpty(existingWsVnet)) {
      lines.push(renderVar('existing_workspace_vnet', existingWsVnet));
    } else {
      lines.push('# existing_workspace_vnet = {');
      lines.push('#   network_configuration = {');
      lines.push('#     virtual_network_id                                   = "/subscriptions/..."');
      lines.push('#     private_subnet_id                                    = "/subscriptions/..."');
      lines.push('#     public_subnet_id                                     = "/subscriptions/..."');
      lines.push('#     private_endpoint_subnet_id                           = "/subscriptions/..."');
      lines.push('#     private_subnet_network_security_group_association_id = "/subscriptions/..."');
      lines.push('#     public_subnet_network_security_group_association_id  = "/subscriptions/..."');
      lines.push('#   }');
      lines.push('#   dns_zone_ids = {');
      lines.push('#     backend = "/subscriptions/..."');
      lines.push('#     dfs     = "/subscriptions/..."');
      lines.push('#     blob    = "/subscriptions/..."');
      lines.push('#   }');
      lines.push('# }');
    }
  } else {
    // Full SRA or BYO Hub: create workspace VNet
    lines.push('# Network mode: create_workspace_vnet defaults to true for SRA-managed network');
    lines.push('# create_workspace_vnet = true');
    lines.push('');

    const workspaceVnet = v('workspace_vnet');
    if (!isEmpty(workspaceVnet)) {
      lines.push(renderVar('workspace_vnet', workspaceVnet));
    } else {
      lines.push('# workspace_vnet = {');
      lines.push('#   cidr = "10.0.4.0/22"');
      lines.push('# }');
    }
  }
  lines.push('');

  // ── Security ──────────────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Security');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  // CMK
  const cmkEnabled = v('cmk_enabled');
  if (cmkEnabled === false) {
    lines.push(renderVar('cmk_enabled', false));
  } else {
    lines.push('# Optional: Disable customer-managed keys if needed (defaults to enabled)');
    lines.push('# cmk_enabled = false');
  }
  lines.push('');

  // Existing CMK IDs (only for BYO modes)
  if (!isFullSra) {
    const existingCmkIds = v('existing_cmk_ids');
    if (!isEmpty(existingCmkIds)) {
      lines.push(renderVar('existing_cmk_ids', existingCmkIds));
      lines.push('');
    }
  }

  // ── Tags ──────────────────────────────────────────────────────────────────
  const tags = v('tags');
  if (!isEmpty(tags)) {
    lines.push(renderVar('tags', tags));
  } else {
    lines.push('tags = {}');
  }
  lines.push('');

  // ── Network Egress ────────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Network Egress Configuration');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  const allowedFqdns = v('allowed_fqdns');
  lines.push(renderVar('allowed_fqdns', isEmpty(allowedFqdns) ? [] : allowedFqdns));

  const hubAllowedUrls = v('hub_allowed_urls');
  lines.push(renderVar('hub_allowed_urls', isEmpty(hubAllowedUrls) ? [] : hubAllowedUrls));
  lines.push('');

  // ── Advanced / Optional ───────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Advanced Configuration');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  // Workspace Security Compliance
  const wsc = v('workspace_security_compliance');
  if (!isEmpty(wsc)) {
    lines.push(renderVar('workspace_security_compliance', wsc));
  } else {
    lines.push('# Optional: Enhanced security compliance');
    lines.push('# workspace_security_compliance = {');
    lines.push('#   compliance_security_profile_enabled   = true');
    lines.push('#   compliance_security_profile_standards = ["HIPAA"]');
    lines.push('#   enhanced_security_monitoring_enabled  = true');
    lines.push('#   automatic_cluster_update_enabled      = true');
    lines.push('# }');
  }
  lines.push('');

  // SAT Configuration
  const satConfig = v('sat_configuration');
  if (!isEmpty(satConfig)) {
    lines.push(renderVar('sat_configuration', satConfig));
    lines.push('');
  }

  // SAT Service Principal
  const satSp = v('sat_service_principal');
  if (!isEmpty(satSp)) {
    lines.push('# SAT Service Principal (sensitive)');
    lines.push(renderVar('sat_service_principal', satSp));
    lines.push('');
  }

  // Resource Group
  const createRg = v('create_workspace_resource_group');
  if (createRg === false) {
    lines.push(renderVar('create_workspace_resource_group', false));
    const existingRgName = v('existing_resource_group_name');
    if (!isEmpty(existingRgName)) {
      lines.push(renderVar('existing_resource_group_name', existingRgName));
    }
    lines.push('');
  }

  // Workspace Name Overrides
  const nameOverrides = v('workspace_name_overrides');
  if (!isEmpty(nameOverrides)) {
    lines.push(renderVar('workspace_name_overrides', nameOverrides));
    lines.push('');
  }

  return lines.join('\n') + '\n';
}
