import { gcpSchema } from '../../schemas/gcp/variables';
import { serializeValue } from './tfvars-serializer';
import type { FormValues, DeploymentMode, SchemaVariable } from '../../schemas/types';

// ─── GCP tfvars generator ──────────────────────────────────────────────────
// Produces a terraform.tfvars string for GCP SRA deployments

/**
 * Look up a schema variable definition by name.
 */
function findVar(name: string): SchemaVariable | undefined {
  return gcpSchema.variables.find((v) => v.name === name);
}

/**
 * Render a single variable assignment line.
 */
function renderVar(
  name: string,
  value: unknown,
  commentOut: boolean = false,
): string {
  const varDef = findVar(name);
  if (!varDef) return '';

  // Required field with no value — show empty string with reminder
  if (
    varDef.required &&
    varDef.terraformType === 'string' &&
    (value === undefined || value === null || value === '')
  ) {
    return `${name} = ""  # Required — fill in before running terraform`;
  }

  // Optional field with no value -- comment it out
  if (commentOut && (value === undefined || value === null || value === '')) {
    return `# ${name} = ""`;
  }

  const serialized = serializeValue(value, varDef.terraformType);
  return `${name} = ${serialized}`;
}

/**
 * Render a variable that is not in the schema (e.g. fixed values).
 */
function renderFixedVar(name: string, value: unknown): string {
  if (typeof value === 'boolean') {
    return `${name} = ${value ? 'true' : 'false'}`;
  }
  if (typeof value === 'string') {
    return `${name} = "${value}"`;
  }
  return `${name} = ${String(value)}`;
}

/**
 * Check if a value is "empty".
 */
function isEmpty(value: unknown): boolean {
  if (value === undefined || value === null || value === '') return true;
  if (Array.isArray(value) && value.length === 0) return true;
  if (typeof value === 'object' && !Array.isArray(value) && Object.keys(value as object).length === 0)
    return true;
  return false;
}

/**
 * Generate terraform.tfvars content for a GCP SRA deployment.
 */
export function generateGcpTfvars(values: FormValues, mode: DeploymentMode): string {
  const merged: FormValues = { ...values, ...mode.fixedValues };
  const v = (name: string): unknown => merged[name];

  const isExistingVpc = mode.id === 'existing-vpc';

  const lines: string[] = [];

  // ── Header ─────────────────────────────────────────────────────────────────
  lines.push('# =============================================================================');
  lines.push('# Configuration Variables for GCP Databricks SRA');
  lines.push(`# Generated by Databricks SRA WebUI on ${new Date().toISOString()}`);
  lines.push(`# Mode: ${mode.label}`);
  lines.push('# =============================================================================');
  lines.push('');

  // ── Account & Identity ────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Account & Identity');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');
  lines.push(renderVar('databricks_account_id', v('databricks_account_id')));
  lines.push(renderVar('databricks_google_service_account', v('databricks_google_service_account')));
  lines.push(renderVar('google_project', v('google_project')));
  lines.push(renderVar('google_region', v('google_region')));
  lines.push(renderVar('workspace_name', v('workspace_name')));

  const accountConsoleUrl = v('account_console_url');
  if (!isEmpty(accountConsoleUrl) && accountConsoleUrl !== 'https://accounts.gcp.databricks.com') {
    lines.push(renderVar('account_console_url', accountConsoleUrl));
  } else {
    lines.push('# account_console_url = "https://accounts.gcp.databricks.com"  # default');
  }

  lines.push(renderVar('admin_user_email', v('admin_user_email')));
  lines.push(renderVar('create_admin_user', v('create_admin_user') ?? false));
  lines.push('');

  // ── Network Configuration ─────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Network Configuration');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  // Fixed value for use_existing_vpc
  lines.push(renderFixedVar('use_existing_vpc', isExistingVpc));
  lines.push('');

  if (isExistingVpc) {
    lines.push(renderVar('existing_vpc_name', v('existing_vpc_name')));
    const existingSubnet = v('existing_subnet_name');
    if (!isEmpty(existingSubnet)) {
      lines.push(renderVar('existing_subnet_name', existingSubnet));
    } else {
      lines.push('# existing_subnet_name = ""');
    }
    lines.push('');
  } else {
    lines.push(renderVar('nodes_ip_cidr_range', v('nodes_ip_cidr_range') ?? '10.0.0.0/16'));
    lines.push('');
  }

  lines.push(renderVar('harden_network', v('harden_network') ?? true));
  lines.push('');

  const ipAddresses = v('ip_addresses');
  lines.push(renderVar('ip_addresses', isEmpty(ipAddresses) ? ['0.0.0.0/0'] : ipAddresses));
  lines.push('');

  // ── PSC Configuration ─────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Private Service Connect (PSC)');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  const usePsc = v('use_psc');
  lines.push(renderVar('use_psc', usePsc ?? false));
  lines.push('');

  if (usePsc) {
    const peSubnet = v('google_pe_subnet');
    if (!isEmpty(peSubnet)) {
      lines.push(renderVar('google_pe_subnet', peSubnet));
    } else {
      lines.push('# google_pe_subnet = ""');
    }

    const peSubnetCidr = v('google_pe_subnet_ip_cidr_range');
    if (!isEmpty(peSubnetCidr)) {
      lines.push(renderVar('google_pe_subnet_ip_cidr_range', peSubnetCidr));
    } else {
      lines.push('# google_pe_subnet_ip_cidr_range = ""');
    }

    const workspacePe = v('workspace_pe');
    if (!isEmpty(workspacePe)) {
      lines.push(renderVar('workspace_pe', workspacePe));
    } else {
      lines.push('# workspace_pe = ""');
    }

    const relayPe = v('relay_pe');
    if (!isEmpty(relayPe)) {
      lines.push(renderVar('relay_pe', relayPe));
    } else {
      lines.push('# relay_pe = ""');
    }

    const workspacePeIp = v('workspace_pe_ip_name');
    if (!isEmpty(workspacePeIp)) {
      lines.push(renderVar('workspace_pe_ip_name', workspacePeIp));
    } else {
      lines.push('# workspace_pe_ip_name = ""');
    }

    const relayPeIp = v('relay_pe_ip_name');
    if (!isEmpty(relayPeIp)) {
      lines.push(renderVar('relay_pe_ip_name', relayPeIp));
    } else {
      lines.push('# relay_pe_ip_name = ""');
    }

    const wsAttachment = v('workspace_service_attachment');
    if (!isEmpty(wsAttachment)) {
      lines.push(renderVar('workspace_service_attachment', wsAttachment));
    } else {
      lines.push('# workspace_service_attachment = ""');
    }

    const relayAttachment = v('relay_service_attachment');
    if (!isEmpty(relayAttachment)) {
      lines.push(renderVar('relay_service_attachment', relayAttachment));
    } else {
      lines.push('# relay_service_attachment = ""');
    }

    if (isExistingVpc) {
      lines.push('');
      lines.push(renderVar('use_existing_PSC_EP', v('use_existing_PSC_EP') ?? false));
    }

    // Existing Databricks VPC endpoints (for shared PSC registrations)
    lines.push('');
    lines.push(renderVar('use_existing_databricks_vpc_eps', v('use_existing_databricks_vpc_eps') ?? false));
    if (v('use_existing_databricks_vpc_eps')) {
      const epWorkspace = v('existing_databricks_vpc_ep_workspace');
      if (!isEmpty(epWorkspace)) {
        lines.push(renderVar('existing_databricks_vpc_ep_workspace', epWorkspace));
      } else {
        lines.push('# existing_databricks_vpc_ep_workspace = ""');
      }
      const epRelay = v('existing_databricks_vpc_ep_relay');
      if (!isEmpty(epRelay)) {
        lines.push(renderVar('existing_databricks_vpc_ep_relay', epRelay));
      } else {
        lines.push('# existing_databricks_vpc_ep_relay = ""');
      }
    }
  } else {
    lines.push('# PSC is disabled. A Cloud NAT will be created for outbound connectivity.');
    lines.push('# Set use_psc = true to use Private Service Connect for fully private access.');
  }
  lines.push('');

  // ── Security ──────────────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Security & Encryption (CMEK)');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  const useExistingCmek = v('use_existing_cmek');
  lines.push(renderVar('use_existing_cmek', useExistingCmek ?? false));
  lines.push('');

  if (useExistingCmek) {
    const keyName = v('key_name');
    if (!isEmpty(keyName)) {
      lines.push(renderVar('key_name', keyName));
    } else {
      lines.push(renderVar('key_name', keyName, true));
    }

    const keyringName = v('keyring_name');
    if (!isEmpty(keyringName)) {
      lines.push(renderVar('keyring_name', keyringName));
    } else {
      lines.push(renderVar('keyring_name', keyringName, true));
    }

    const cmekResourceId = v('cmek_resource_id');
    if (!isEmpty(cmekResourceId)) {
      lines.push(renderVar('cmek_resource_id', cmekResourceId));
    } else {
      lines.push(renderVar('cmek_resource_id', cmekResourceId, true));
    }
  }
  lines.push('');

  // ── Advanced ──────────────────────────────────────────────────────────────
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('# Advanced Configuration');
  lines.push('# -----------------------------------------------------------------------------');
  lines.push('');

  // Private Access Settings
  const useExistingPas = v('use_existing_pas');
  if (useExistingPas) {
    lines.push(renderVar('use_existing_pas', true));
    const pasId = v('existing_pas_id');
    if (!isEmpty(pasId)) {
      lines.push(renderVar('existing_pas_id', pasId));
    } else {
      lines.push('# existing_pas_id = ""');
    }
    lines.push('');
  }

  // Metastore
  lines.push(renderVar('provision_regional_metastore', v('provision_regional_metastore') ?? true));

  const metastoreId = v('regional_metastore_id');
  if (!isEmpty(metastoreId)) {
    lines.push(renderVar('regional_metastore_id', metastoreId));
  } else {
    lines.push('# regional_metastore_id = ""');
  }
  lines.push('');

  return lines.join('\n') + '\n';
}
