// ─── README generator for the deployment ZIP ──────────────────────────────

const PROVIDER_META: Record<
  string,
  { name: string; dir: string; authVars: string[]; authDocs: string }
> = {
  aws: {
    name: 'AWS',
    dir: 'aws/tf',
    authVars: [
      'AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY (AWS CLI credentials)',
      'DATABRICKS_CLIENT_ID / DATABRICKS_CLIENT_SECRET (Databricks OAuth M2M)',
    ],
    authDocs: 'https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html',
  },
  azure: {
    name: 'Azure',
    dir: 'azure/tf',
    authVars: [
      'ARM_CLIENT_ID / ARM_CLIENT_SECRET / ARM_TENANT_ID (Azure service principal)',
      'DATABRICKS_CLIENT_ID / DATABRICKS_CLIENT_SECRET (Databricks OAuth M2M)',
    ],
    authDocs: 'https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret',
  },
  gcp: {
    name: 'GCP',
    dir: 'gcp/modules/workspace_deployment',
    authVars: [
      'DATABRICKS_GOOGLE_SERVICE_ACCOUNT (Google service account email)',
      'GOOGLE_CREDENTIALS (path to service account key JSON)',
      'DATABRICKS_CLIENT_ID / DATABRICKS_CLIENT_SECRET (Databricks OAuth M2M)',
    ],
    authDocs: 'https://cloud.google.com/docs/authentication/application-default-credentials',
  },
};

/**
 * Generate a deployment README.md for inclusion in the ZIP package.
 */
export function generateReadme(provider: string, mode: string): string {
  const meta = PROVIDER_META[provider] ?? PROVIDER_META.aws;
  const modeLabel = mode.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

  const authList = meta.authVars.map((v) => `- \`${v}\``).join('\n');

  return `# Databricks SRA ${meta.name} Deployment Configuration

> Generated by **Databricks SRA WebUI**
> Deployment mode: **${modeLabel}**

## What is this?

This archive contains a pre-configured \`terraform.tfvars\` file for deploying the
Databricks Security Reference Architecture (SRA) on ${meta.name}. The values were
generated through the Databricks SRA WebUI web wizard.

## Quick Start

### 1. Clone the SRA repository

\`\`\`bash
git clone https://github.com/databricks/terraform-databricks-sra.git
cd terraform-databricks-sra
\`\`\`

### 2. Copy terraform.tfvars

Copy the \`terraform.tfvars\` file from this archive into the correct directory:

\`\`\`bash
cp terraform.tfvars terraform-databricks-sra/${meta.dir}/
\`\`\`

### 3. Configure authentication

Set up authentication for ${meta.name} and Databricks using standard provider
environment variables. An \`.env.example\` file is included for reference.

**Required credentials:**
${authList}

\`\`\`bash
cp .env.example .env
# Edit .env with your credentials
source .env
\`\`\`

See: ${meta.authDocs}

### 4. Deploy with Terraform

\`\`\`bash
cd terraform-databricks-sra/${meta.dir}/
terraform init
terraform plan
terraform apply
\`\`\`

## Critical Next Steps

After deploying the SRA, you should:

- **Implement front-end mitigation** — Configure IP Access Lists or Front-End PrivateLink/PSC to restrict workspace access.
- **Configure SSO, MFA, and SCIM** — Set up identity federation, multi-factor authentication, and automated user provisioning.
- **Deploy Security Analysis Tool (SAT)** — Enable continuous security monitoring of your workspace configuration.

## Documentation

- [Databricks SRA Documentation](https://databricks.github.io/terraform-databricks-sra/)
- [Databricks SRA Repository](https://github.com/databricks/terraform-databricks-sra)
- [Databricks Security Best Practices](https://docs.databricks.com/en/security/reference-architecture.html)
- [Terraform Provider for Databricks](https://registry.terraform.io/providers/databricks/databricks/latest/docs)
`;
}
