import type { DeploymentMode } from '../types';

export const azureDeploymentModes: DeploymentMode[] = [
  {
    id: 'full-sra',
    label: 'Full SRA',
    description:
      'SRA creates and manages all infrastructure including hub VNet with Azure Firewall, Key Vault, spoke workspace VNet with private endpoints, NCC, network policy, and Unity Catalog metastore.',
    recommended: true,
    variables: [
      'databricks_account_id',
      'subscription_id',
      'location',
      'resource_suffix',
      'hub_resource_suffix',
      'hub_vnet_cidr',
      'workspace_vnet',
      'cmk_enabled',
      'tags',
      'workspace_security_compliance',
      'allowed_fqdns',
      'hub_allowed_urls',
      'sat_configuration',
      'sat_service_principal',
      'workspace_name_overrides',
      'create_workspace_resource_group',
      'existing_resource_group_name',
    ],
    fixedValues: { create_hub: true, create_workspace_vnet: true },
    requiredOverrides: { hub_resource_suffix: true, hub_vnet_cidr: true },
    defaultOverrides: {},
  },
  {
    id: 'byo-hub',
    label: 'BYO Hub',
    description:
      'You provide existing hub infrastructure (VNet, Key Vault, metastore, NCC, network policy). SRA creates spoke workspace VNet, private endpoints, and UC storage account. Note: SAT is not available in this mode.',
    variables: [
      'databricks_account_id',
      'subscription_id',
      'location',
      'resource_suffix',
      'databricks_metastore_id',
      'existing_hub_vnet',
      'existing_ncc_id',
      'existing_ncc_name',
      'existing_network_policy_id',
      'workspace_vnet',
      'existing_cmk_ids',
      'cmk_enabled',
      'tags',
      'allowed_fqdns',
      'hub_allowed_urls',
      'workspace_security_compliance',
      'sat_configuration',
      'sat_service_principal',
      'workspace_name_overrides',
      'create_workspace_resource_group',
      'existing_resource_group_name',
    ],
    fixedValues: { create_hub: false, create_workspace_vnet: true },
    requiredOverrides: {
      databricks_metastore_id: true,
      existing_hub_vnet: true,
      existing_ncc_id: true,
      existing_network_policy_id: true,
    },
    defaultOverrides: {},
  },
  {
    id: 'byo-spoke',
    label: 'BYO Spoke Network',
    description:
      'You provide both hub and spoke infrastructure. SRA creates the workspace, back-end private endpoints, and UC storage account.',
    variables: [
      'databricks_account_id',
      'subscription_id',
      'location',
      'resource_suffix',
      'databricks_metastore_id',
      'existing_hub_vnet',
      'existing_ncc_id',
      'existing_ncc_name',
      'existing_network_policy_id',
      'existing_workspace_vnet',
      'existing_cmk_ids',
      'cmk_enabled',
      'tags',
      'allowed_fqdns',
      'hub_allowed_urls',
      'workspace_security_compliance',
      'sat_configuration',
      'sat_service_principal',
      'workspace_name_overrides',
      'create_workspace_resource_group',
      'existing_resource_group_name',
    ],
    fixedValues: { create_hub: false, create_workspace_vnet: false },
    requiredOverrides: {
      databricks_metastore_id: true,
      existing_hub_vnet: true,
      existing_ncc_id: true,
      existing_network_policy_id: true,
      existing_workspace_vnet: true,
    },
    defaultOverrides: {},
  },
];
