import type { DeploymentMode } from '../types';

export const gcpDeploymentModes: DeploymentMode[] = [
  {
    id: 'new-vpc',
    label: 'New VPC',
    description:
      'SRA creates a customer-managed VPC with subnets, Cloud KMS (CMEK), and private Cloud DNS. When PSC is disabled (default), a Cloud Router and Cloud NAT are created for outbound connectivity. Enable PSC for back-end private connectivity to the Databricks control plane via Google Cloud backbone.',
    recommended: true,
    variables: [
      'databricks_account_id',
      'databricks_google_service_account',
      'google_project',
      'google_region',
      'workspace_name',
      'admin_user_email',
      'nodes_ip_cidr_range',
      'harden_network',
      'ip_addresses',
      'use_psc',
      'google_pe_subnet',
      'google_pe_subnet_ip_cidr_range',
      'workspace_pe',
      'relay_pe',
      'workspace_pe_ip_name',
      'relay_pe_ip_name',
      'workspace_service_attachment',
      'relay_service_attachment',
      'use_existing_databricks_vpc_eps',
      'existing_databricks_vpc_ep_workspace',
      'existing_databricks_vpc_ep_relay',
      'use_existing_cmek',
      'key_name',
      'keyring_name',
      'cmek_resource_id',
      'account_console_url',
      'create_admin_user',
      'can_create_workspaces',
      'use_existing_pas',
      'existing_pas_id',
      'provision_regional_metastore',
      'regional_metastore_id',
    ],
    fixedValues: { use_existing_vpc: false },
    requiredOverrides: {},
    defaultOverrides: { nodes_ip_cidr_range: '10.0.0.0/16' },
  },
  {
    id: 'existing-vpc',
    label: 'Existing VPC',
    description:
      'Deploy into your existing customer-managed VPC. SRA configures workspace networking, Cloud KMS, and optionally Private Service Connect. You can use existing PSC endpoints and Databricks VPC endpoint registrations.',
    variables: [
      'databricks_account_id',
      'databricks_google_service_account',
      'google_project',
      'google_region',
      'workspace_name',
      'admin_user_email',
      'existing_vpc_name',
      'existing_subnet_name',
      'harden_network',
      'ip_addresses',
      'use_psc',
      'use_existing_PSC_EP',
      'google_pe_subnet',
      'google_pe_subnet_ip_cidr_range',
      'workspace_pe',
      'relay_pe',
      'workspace_pe_ip_name',
      'relay_pe_ip_name',
      'workspace_service_attachment',
      'relay_service_attachment',
      'use_existing_databricks_vpc_eps',
      'existing_databricks_vpc_ep_workspace',
      'existing_databricks_vpc_ep_relay',
      'use_existing_cmek',
      'key_name',
      'keyring_name',
      'cmek_resource_id',
      'account_console_url',
      'create_admin_user',
      'can_create_workspaces',
      'use_existing_pas',
      'existing_pas_id',
      'provision_regional_metastore',
      'regional_metastore_id',
    ],
    fixedValues: { use_existing_vpc: true },
    requiredOverrides: { existing_vpc_name: true },
    defaultOverrides: {},
  },
];
