import type { SchemaVariable, ProviderSchema } from '../types';
import { GCP_REGIONS } from './regions';
import { gcpDeploymentModes } from './modes';

// ─── All user-facing GCP SRA variables ──────────────────────────────────────
// Mapped from terraform-databricks-sra/gcp/tf/variables.tf

export const gcpVariables: SchemaVariable[] = [
  // ── Account & Identity group ────────────────────────────────────────────────
  {
    name: 'databricks_account_id',
    terraformType: 'string',
    description: '(Required) The Databricks account ID for account-level operations',
    required: true,
    sensitive: false,
    nullable: false,
    validation: [
      {
        type: 'uuid',
        message: 'Must be a valid UUID (e.g. 00000000-0000-0000-0000-000000000000).',
      },
    ],
    ui: {
      label: 'Databricks Account ID',
      group: 'account',
      order: 1,
      inputType: 'text',
      placeholder: '00000000-0000-0000-0000-000000000000',
      helpText: 'Your Databricks account ID (UUID format).',
      width: 'half',
    },
  },
  {
    name: 'databricks_google_service_account',
    terraformType: 'string',
    description: '(Required) The Google Service Account used by Databricks',
    required: true,
    sensitive: false,
    nullable: false,
    ui: {
      label: 'Databricks Google Service Account',
      group: 'account',
      order: 2,
      inputType: 'text',
      placeholder: 'databricks@project.iam.gserviceaccount.com',
      helpText: 'The Google service account email used by the Databricks control plane.',
      width: 'full',
    },
  },
  {
    name: 'google_project',
    terraformType: 'string',
    description: '(Required) The Google Cloud project ID',
    required: true,
    sensitive: false,
    nullable: false,
    ui: {
      label: 'Google Project ID',
      group: 'account',
      order: 3,
      inputType: 'text',
      placeholder: 'my-gcp-project',
      helpText: 'The GCP project where resources will be deployed.',
      width: 'half',
    },
  },
  {
    name: 'google_region',
    terraformType: 'string',
    description: '(Required) The Google Cloud region for deployment',
    required: true,
    sensitive: false,
    nullable: false,
    validation: [
      {
        type: 'enum',
        value: GCP_REGIONS.map((r) => r.value),
        message: 'Must be a valid GCP region.',
      },
    ],
    ui: {
      label: 'Google Cloud Region',
      group: 'account',
      order: 4,
      inputType: 'select',
      options: GCP_REGIONS,
      helpText: 'The GCP region where all resources will be deployed.',
      width: 'half',
    },
  },
  {
    name: 'workspace_name',
    terraformType: 'string',
    description: '(Required) Name for the Databricks workspace',
    required: true,
    sensitive: false,
    nullable: false,
    ui: {
      label: 'Workspace Name',
      group: 'account',
      order: 5,
      inputType: 'text',
      placeholder: 'my-databricks-workspace',
      helpText: 'Name of the Databricks workspace to create.',
      width: 'half',
    },
  },
  {
    name: 'admin_user_email',
    terraformType: 'string',
    description: '(Required) Admin user email for workspace and catalog management',
    required: true,
    sensitive: false,
    nullable: false,
    validation: [
      {
        type: 'email',
        message: 'Must be a valid email address.',
      },
    ],
    ui: {
      label: 'Admin User Email',
      group: 'account',
      order: 6,
      inputType: 'email',
      placeholder: 'admin@example.com',
      helpText: 'Email address of the admin user for workspace and Unity Catalog management.',
      width: 'half',
    },
  },

  // ── Network group ───────────────────────────────────────────────────────────
  {
    name: 'nodes_ip_cidr_range',
    terraformType: 'string',
    description: '(Optional) CIDR range for workspace node IPs',
    required: false,
    sensitive: false,
    default: '10.0.0.0/16',
    nullable: false,
    validation: [
      {
        type: 'cidr',
        message: 'Must be a valid CIDR block (e.g. 10.0.0.0/16).',
      },
    ],
    ui: {
      label: 'Nodes IP CIDR Range',
      group: 'network',
      order: 1,
      inputType: 'cidr',
      placeholder: '10.0.0.0/16',
      helpText: 'CIDR block for GKE node IP addresses.',
      width: 'half',
    },
  },
  {
    name: 'existing_vpc_name',
    terraformType: 'string',
    description: '(Required for existing-vpc) Name of the existing VPC to use',
    required: false,
    sensitive: false,
    nullable: false,
    ui: {
      label: 'Existing VPC Name',
      group: 'network',
      order: 2,
      inputType: 'text',
      placeholder: 'my-existing-vpc',
      helpText: 'Name of the existing GCP VPC to use for the workspace.',
      width: 'half',
    },
  },
  {
    name: 'existing_subnet_name',
    terraformType: 'string',
    description: '(Required for existing-vpc) Name of the existing subnet to use',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Existing Subnet Name',
      group: 'network',
      order: 3,
      inputType: 'text',
      placeholder: 'my-existing-subnet',
      helpText: 'Name of the existing GCP subnet within the VPC.',
      visibleWhen: [{ field: 'use_existing_vpc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'harden_network',
    terraformType: 'bool',
    description: '(Optional) Whether to apply network hardening rules',
    required: false,
    sensitive: false,
    default: true,
    nullable: false,
    ui: {
      label: 'Harden Network',
      group: 'network',
      order: 3,
      inputType: 'checkbox',
      helpText: 'Apply restrictive firewall rules and network policies for enhanced security.',
      width: 'half',
    },
  },
  {
    name: 'ip_addresses',
    terraformType: 'list(string)',
    description: '(Optional) List of IP addresses/CIDRs for network access',
    required: false,
    sensitive: false,
    default: ['0.0.0.0/0'],
    nullable: false,
    ui: {
      label: 'IP Addresses',
      group: 'network',
      order: 4,
      inputType: 'list-editor',
      placeholder: '0.0.0.0/0',
      helpText: 'List of IP addresses or CIDR blocks allowed for network access.',
      width: 'full',
    },
  },
  {
    name: 'use_psc',
    terraformType: 'bool',
    description: '(Optional) Whether to use Private Service Connect (PSC)',
    required: false,
    sensitive: false,
    default: false,
    nullable: false,
    ui: {
      label: 'Use Private Service Connect (PSC)',
      group: 'network',
      order: 5,
      inputType: 'checkbox',
      helpText: 'When disabled (default), a Cloud NAT is created and the workspace requires outbound internet access. When enabled, Private Service Connect endpoints provide fully private connectivity with no internet required.',
      width: 'half',
    },
  },
  {
    name: 'google_pe_subnet',
    terraformType: 'string',
    description: '(Optional) Name of the Private Endpoint subnet',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'PE Subnet Name',
      group: 'network',
      order: 6,
      inputType: 'text',
      placeholder: 'pe-subnet',
      helpText: 'Name of the subnet for Private Service Connect endpoints.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'google_pe_subnet_ip_cidr_range',
    terraformType: 'string',
    description: '(Optional) CIDR range for the PE subnet',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    validation: [
      {
        type: 'cidr',
        message: 'Must be a valid CIDR block.',
      },
    ],
    ui: {
      label: 'PE Subnet CIDR',
      group: 'network',
      order: 7,
      inputType: 'cidr',
      placeholder: '10.1.0.0/24',
      helpText: 'CIDR block for the Private Endpoint subnet.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'workspace_pe',
    terraformType: 'string',
    description: '(Optional) Name of the workspace Private Endpoint',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Workspace PE Name',
      group: 'network',
      order: 8,
      inputType: 'text',
      placeholder: 'workspace-pe',
      helpText: 'Name for the workspace Private Service Connect endpoint.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'relay_pe',
    terraformType: 'string',
    description: '(Optional) Name of the relay Private Endpoint',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Relay PE Name',
      group: 'network',
      order: 9,
      inputType: 'text',
      placeholder: 'relay-pe',
      helpText: 'Name for the relay Private Service Connect endpoint.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'workspace_pe_ip_name',
    terraformType: 'string',
    description: '(Optional) IP name for the workspace PE',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Workspace PE IP Name',
      group: 'network',
      order: 10,
      inputType: 'text',
      placeholder: 'workspace-pe-ip',
      helpText: 'IP address name for the workspace Private Service Connect endpoint.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'relay_pe_ip_name',
    terraformType: 'string',
    description: '(Optional) IP name for the relay PE',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Relay PE IP Name',
      group: 'network',
      order: 11,
      inputType: 'text',
      placeholder: 'relay-pe-ip',
      helpText: 'IP address name for the relay Private Service Connect endpoint.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'workspace_service_attachment',
    terraformType: 'string',
    description: '(Optional) Service attachment for the workspace PSC',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Workspace Service Attachment',
      group: 'network',
      order: 12,
      inputType: 'text',
      placeholder: 'projects/.../regions/.../serviceAttachments/...',
      helpText: 'Service attachment URI for the workspace Private Service Connect.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'full',
    },
  },
  {
    name: 'relay_service_attachment',
    terraformType: 'string',
    description: '(Optional) Service attachment for the relay PSC',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Relay Service Attachment',
      group: 'network',
      order: 13,
      inputType: 'text',
      placeholder: 'projects/.../regions/.../serviceAttachments/...',
      helpText: 'Service attachment URI for the relay Private Service Connect.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'full',
    },
  },
  {
    name: 'use_existing_PSC_EP',
    terraformType: 'bool',
    description: '(Optional) Whether to use existing PSC endpoints',
    required: false,
    sensitive: false,
    default: false,
    nullable: false,
    ui: {
      label: 'Use Existing PSC Endpoints',
      group: 'network',
      order: 14,
      inputType: 'checkbox',
      helpText: 'Use existing Private Service Connect endpoints instead of creating new ones.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },

  {
    name: 'use_existing_databricks_vpc_eps',
    terraformType: 'bool',
    description: '(Optional) Whether to use existing registered Databricks VPC endpoints for PSC',
    required: false,
    sensitive: false,
    default: false,
    nullable: false,
    ui: {
      label: 'Use Existing Databricks VPC Endpoints',
      group: 'network',
      order: 15,
      inputType: 'checkbox',
      helpText: 'If PSC endpoints have already been registered by other workspaces, existing Databricks VPC endpoints must be used since a PSC cannot be registered more than once.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'existing_databricks_vpc_ep_workspace',
    terraformType: 'string',
    description: '(Required if use_existing_databricks_vpc_eps) Existing Databricks VPC Endpoint ID for workspace',
    required: false,
    sensitive: false,
    nullable: false,
    ui: {
      label: 'Existing Workspace VPC Endpoint ID',
      group: 'network',
      order: 16,
      inputType: 'text',
      placeholder: 'databricks-vpc-ep-workspace-id',
      helpText: 'Existing Databricks VPC Endpoint ID for the workspace PSC endpoint.',
      visibleWhen: [
        { field: 'use_psc', operator: 'eq', value: true },
        { field: 'use_existing_databricks_vpc_eps', operator: 'eq', value: true },
      ],
      width: 'full',
    },
  },
  {
    name: 'existing_databricks_vpc_ep_relay',
    terraformType: 'string',
    description: '(Required if use_existing_databricks_vpc_eps) Existing Databricks VPC Endpoint ID for relay',
    required: false,
    sensitive: false,
    nullable: false,
    ui: {
      label: 'Existing Relay VPC Endpoint ID',
      group: 'network',
      order: 17,
      inputType: 'text',
      placeholder: 'databricks-vpc-ep-relay-id',
      helpText: 'Existing Databricks VPC Endpoint ID for the relay PSC endpoint.',
      visibleWhen: [
        { field: 'use_psc', operator: 'eq', value: true },
        { field: 'use_existing_databricks_vpc_eps', operator: 'eq', value: true },
      ],
      width: 'full',
    },
  },

  // ── Security group ──────────────────────────────────────────────────────────
  {
    name: 'use_existing_cmek',
    terraformType: 'bool',
    description: '(Optional) Whether to use existing CMEK keys',
    required: false,
    sensitive: false,
    default: false,
    nullable: false,
    ui: {
      label: 'Use Existing CMEK',
      group: 'security',
      order: 1,
      inputType: 'checkbox',
      helpText: 'Use an existing Customer-Managed Encryption Key (CMEK) instead of creating a new one.',
      width: 'half',
    },
  },
  {
    name: 'key_name',
    terraformType: 'string',
    description: '(Optional) Name of the CMEK key',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Key Name',
      group: 'security',
      order: 2,
      inputType: 'text',
      placeholder: 'my-cmek-key',
      helpText: 'Name of the Cloud KMS key to use for encryption. Required when using existing CMEK.',
      visibleWhen: [{ field: 'use_existing_cmek', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'keyring_name',
    terraformType: 'string',
    description: '(Optional) Name of the CMEK keyring',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Keyring Name',
      group: 'security',
      order: 3,
      inputType: 'text',
      placeholder: 'my-keyring',
      helpText: 'Name of the Cloud KMS keyring. Required when using existing CMEK.',
      visibleWhen: [{ field: 'use_existing_cmek', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'cmek_resource_id',
    terraformType: 'string',
    description: '(Optional) Full resource ID of the CMEK key',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'CMEK Resource ID',
      group: 'security',
      order: 4,
      inputType: 'text',
      placeholder: 'projects/.../locations/.../keyRings/.../cryptoKeys/...',
      helpText: 'Full resource ID of the CMEK key. Alternative to specifying key_name and keyring_name separately.',
      visibleWhen: [{ field: 'use_existing_cmek', operator: 'eq', value: true }],
      width: 'full',
    },
  },

  // ── Service Account & Access (account group) ────────────────────────────────
  {
    name: 'account_console_url',
    terraformType: 'string',
    description: '(Optional) Databricks account console URL for GCP',
    required: false,
    sensitive: false,
    default: 'https://accounts.gcp.databricks.com',
    nullable: false,
    ui: {
      label: 'Account Console URL',
      group: 'account',
      order: 10,
      inputType: 'text',
      placeholder: 'https://accounts.gcp.databricks.com',
      helpText: 'Databricks account console URL. Only change this for non-standard environments.',
      width: 'full',
    },
  },
  {
    name: 'create_admin_user',
    terraformType: 'bool',
    description: '(Optional) Whether to create an admin user in the workspace',
    required: false,
    sensitive: false,
    default: false,
    nullable: false,
    ui: {
      label: 'Create Admin User',
      group: 'account',
      order: 11,
      inputType: 'checkbox',
      helpText: 'Create and assign the admin user specified in admin_user_email to the workspace.',
      width: 'half',
    },
  },
  {
    name: 'can_create_workspaces',
    terraformType: 'bool',
    description: '(Optional) Whether the Databricks Google service account can create additional workspaces',
    required: false,
    sensitive: false,
    default: true,
    nullable: false,
    ui: {
      label: 'Service Account Can Create Workspaces',
      group: 'account',
      order: 12,
      inputType: 'checkbox',
      helpText: 'When enabled, grants the Databricks Google service account permission to create additional workspaces in this project. Disable for stricter least-privilege if you only need this single workspace.',
      width: 'half',
    },
  },
  {
    name: 'use_existing_pas',
    terraformType: 'bool',
    description: '(Optional) Whether to use existing Private Access Settings',
    required: false,
    sensitive: false,
    default: false,
    nullable: false,
    ui: {
      label: 'Use Existing Private Access Settings',
      group: 'advanced',
      order: 2,
      inputType: 'checkbox',
      helpText: 'Use an existing Private Access Settings resource instead of creating a new one. Rarely needed.',
      visibleWhen: [{ field: 'use_psc', operator: 'eq', value: true }],
      width: 'half',
    },
  },
  {
    name: 'existing_pas_id',
    terraformType: 'string',
    description: '(Optional) ID of existing Private Access Settings',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Existing Private Access Settings ID',
      group: 'advanced',
      order: 3,
      inputType: 'text',
      placeholder: 'pas-id',
      helpText: 'The ID of the existing Private Access Settings. Required when use_existing_pas is true.',
      visibleWhen: [
        { field: 'use_psc', operator: 'eq', value: true },
        { field: 'use_existing_pas', operator: 'eq', value: true },
      ],
      width: 'full',
    },
  },
  {
    name: 'provision_regional_metastore',
    terraformType: 'bool',
    description: '(Optional) Whether to provision a regional Unity Catalog metastore',
    required: false,
    sensitive: false,
    default: true,
    nullable: false,
    ui: {
      label: 'Provision Regional Metastore',
      group: 'advanced',
      order: 5,
      inputType: 'checkbox',
      helpText: 'Create a new regional Unity Catalog metastore. Disable if one already exists.',
      width: 'half',
    },
  },
  {
    name: 'regional_metastore_id',
    terraformType: 'string',
    description: '(Optional) ID of an existing regional metastore to use',
    required: false,
    sensitive: false,
    default: '',
    nullable: false,
    ui: {
      label: 'Regional Metastore ID',
      group: 'advanced',
      order: 6,
      inputType: 'text',
      placeholder: '00000000-0000-0000-0000-000000000000',
      helpText: 'ID of an existing Unity Catalog metastore. Only needed when not provisioning a new one.',
      visibleWhen: [{ field: 'provision_regional_metastore', operator: 'eq', value: false }],
      width: 'half',
    },
  },
];

// ─── Full provider schema ───────────────────────────────────────────────────

export const gcpSchema: ProviderSchema = {
  provider: 'gcp',
  displayName: 'Google Cloud Platform',
  description: 'Deploy Databricks on GCP with VPC, PSC, CMEK, and security hardening',
  deploymentModes: gcpDeploymentModes,
  variables: gcpVariables,
};
