import type { DeploymentMode } from '../types';

export const awsDeploymentModes: DeploymentMode[] = [
  {
    id: 'isolated',
    label: 'Isolated Network',
    description:
      'SRA creates a new VPC that prevents any traffic to the public internet, limiting traffic to AWS private endpoints for AWS services or the Databricks control plane. A Network Connectivity Configuration (NCC) and restrictive network policy are applied for serverless compute.',
    recommended: true,
    variables: [
      'resource_prefix',
      'region',
      'aws_account_id',
      'databricks_account_id',
      'admin_user',
      'network_configuration',
      'vpc_cidr_range',
      'private_subnets_cidr',
      'privatelink_subnets_cidr',
      'sg_egress_ports',
      'metastore_exists',
      'audit_log_delivery_exists',
      'enable_security_analysis_tool',
      'enable_compliance_security_profile',
      'compliance_standards',
      'cmk_admin_arn',
      'deployment_name',
      'databricks_gov_shard',
    ],
    fixedValues: { network_configuration: 'isolated' },
    requiredOverrides: {},
    defaultOverrides: {
      vpc_cidr_range: '10.0.0.0/18',
      private_subnets_cidr: ['10.0.0.0/22', '10.0.4.0/22', '10.0.8.0/22'],
      privatelink_subnets_cidr: ['10.0.28.0/26', '10.0.28.64/26', '10.0.28.128/26'],
      sg_egress_ports: [443, 2443, 5432, 6666, 8443, 8444, 8445, 8446, 8447, 8448, 8449, 8450, 8451],
    },
  },
  {
    id: 'custom',
    label: 'Custom Network (BYO VPC)',
    description:
      'Allows you to specify your own VPC ID, subnet IDs, security group IDs, and PrivateLink endpoint IDs. Recommended when networking assets are created in different pipelines or pre-assigned by a centralized infrastructure team.',
    variables: [
      'resource_prefix',
      'region',
      'aws_account_id',
      'databricks_account_id',
      'admin_user',
      'network_configuration',
      'custom_vpc_id',
      'custom_private_subnet_ids',
      'custom_sg_id',
      'custom_relay_vpce_id',
      'custom_workspace_vpce_id',
      'metastore_exists',
      'audit_log_delivery_exists',
      'enable_security_analysis_tool',
      'enable_compliance_security_profile',
      'compliance_standards',
      'cmk_admin_arn',
      'deployment_name',
      'databricks_gov_shard',
    ],
    fixedValues: { network_configuration: 'custom' },
    requiredOverrides: {
      custom_vpc_id: true,
      custom_private_subnet_ids: true,
      custom_sg_id: true,
      custom_relay_vpce_id: true,
      custom_workspace_vpce_id: true,
    },
    defaultOverrides: {},
  },
];
