import type { SchemaVariable, ProviderSchema } from '../types';
import { AWS_REGIONS } from './regions';
import { awsDeploymentModes } from './modes';

// ─── All user-facing AWS SRA variables ──────────────────────────────────────
// Mapped exactly from terraform-databricks-sra/aws/tf/variables.tf

export const awsVariables: SchemaVariable[] = [
  // ── Account & Identity group ────────────────────────────────────────────────
  {
    name: 'resource_prefix',
    terraformType: 'string',
    description: 'Prefix for the resource names.',
    required: true,
    sensitive: false,
    nullable: false,
    validation: [
      {
        type: 'regex',
        value: '^[a-z0-9-.]{1,26}$',
        message: 'Invalid resource prefix. Allowed 40 characters containing only a-z, 0-9, -, .',
      },
    ],
    ui: {
      label: 'Resource Prefix',
      group: 'account',
      order: 1,
      inputType: 'text',
      placeholder: 'my-sra-deploy',
      helpText: 'A short prefix added to all created resources. Only lowercase letters, numbers, hyphens, and dots (max 26 characters).',
      width: 'half',
    },
  },
  {
    name: 'region',
    terraformType: 'string',
    description: 'AWS region code. (e.g. us-east-1)',
    required: true,
    sensitive: false,
    nullable: false,
    validation: [
      {
        type: 'enum',
        value: AWS_REGIONS.map((r) => r.value),
        message:
          'Valid values for var: region are (ap-northeast-1, ap-northeast-2, ap-south-1, ap-southeast-1, ap-southeast-2, ap-southeast-3, ca-central-1, eu-central-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, us-east-1, us-east-2, us-west-1, us-west-2, us-gov-west-1).',
      },
    ],
    ui: {
      label: 'AWS Region',
      group: 'account',
      order: 2,
      inputType: 'select',
      options: AWS_REGIONS,
      helpText: 'The AWS region where all resources will be deployed.',
      width: 'half',
    },
  },
  {
    name: 'aws_account_id',
    terraformType: 'string',
    description: 'ID of the AWS account.',
    required: true,
    sensitive: true,
    nullable: false,
    ui: {
      label: 'AWS Account ID',
      group: 'account',
      order: 3,
      inputType: 'sensitive',
      placeholder: '123456789012',
      helpText: 'Your 12-digit AWS account ID.',
      width: 'half',
    },
  },
  {
    name: 'databricks_account_id',
    terraformType: 'string',
    description: 'ID of the Databricks account.',
    required: true,
    sensitive: true,
    nullable: false,
    ui: {
      label: 'Databricks Account ID',
      group: 'account',
      order: 4,
      inputType: 'sensitive',
      placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
      helpText: 'Your Databricks account ID (UUID format).',
      width: 'half',
    },
  },
  {
    name: 'admin_user',
    terraformType: 'string',
    description: 'Email of the admin user for the workspace and workspace catalog.',
    required: true,
    sensitive: false,
    nullable: false,
    validation: [
      {
        type: 'email',
        message: 'Must be a valid email address.',
      },
    ],
    ui: {
      label: 'Admin User Email',
      group: 'account',
      order: 5,
      inputType: 'email',
      placeholder: 'admin@company.com',
      helpText: 'Email address for the workspace admin. Used for workspace and workspace catalog management.',
      width: 'half',
    },
  },
  {
    name: 'databricks_gov_shard',
    terraformType: 'string',
    description: 'Databricks GovCloud shard type (civilian or dod). Only applicable for us-gov-west-1 region.',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    validation: [
      {
        type: 'enum',
        value: ['civilian', 'dod'],
        message: 'Invalid databricks_gov_shard. Allowed values are: null, civilian, dod.',
      },
    ],
    ui: {
      label: 'GovCloud Shard',
      group: 'account',
      order: 6,
      inputType: 'select',
      options: [
        { value: 'civilian', label: 'Civilian' },
        { value: 'dod', label: 'DoD' },
      ],
      visibleWhen: [{ field: 'region', operator: 'eq', value: 'us-gov-west-1' }],
      helpText: 'Select the GovCloud shard type. Only applicable when region is us-gov-west-1.',
      width: 'half',
    },
  },

  // ── Network group ───────────────────────────────────────────────────────────
  {
    name: 'network_configuration',
    terraformType: 'string',
    description: 'The type of network set-up for the workspace network configuration.',
    required: true,
    sensitive: false,
    nullable: false,
    validation: [
      {
        type: 'enum',
        value: ['custom', 'isolated'],
        message: 'Invalid network configuration. Allowed values are: custom, isolated.',
      },
    ],
    ui: {
      label: 'Network Configuration',
      group: 'hidden',
      order: 0,
      inputType: 'select',
      options: [
        { value: 'isolated', label: 'Isolated' },
        { value: 'custom', label: 'Custom' },
      ],
      helpText: 'Set automatically by the deployment mode selection.',
    },
  },
  {
    name: 'vpc_cidr_range',
    terraformType: 'string',
    description: 'CIDR range for the VPC.',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    validation: [
      {
        type: 'cidr',
        message: 'Must be a valid CIDR block (e.g. 10.0.0.0/18).',
      },
    ],
    ui: {
      label: 'VPC CIDR Range',
      group: 'network',
      order: 1,
      inputType: 'cidr',
      placeholder: '10.0.0.0/18',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'isolated' }],
      helpText: 'CIDR range for the new VPC created by the SRA.',
      width: 'full',
    },
  },
  {
    name: 'private_subnets_cidr',
    terraformType: 'list(string)',
    description: 'CIDR blocks for private subnets.',
    required: false,
    sensitive: false,
    default: [null],
    nullable: true,
    validation: [
      {
        type: 'cidr',
        message: 'Each entry must be a valid CIDR block.',
      },
    ],
    ui: {
      label: 'Private Subnet CIDRs',
      group: 'network',
      order: 2,
      inputType: 'cidr-list',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'isolated' }],
      helpText: 'CIDR blocks for private subnets (one per availability zone, typically 3).',
      width: 'full',
    },
  },
  {
    name: 'privatelink_subnets_cidr',
    terraformType: 'list(string)',
    description: 'CIDR blocks for private link subnets.',
    required: false,
    sensitive: false,
    default: [null],
    nullable: true,
    validation: [
      {
        type: 'cidr',
        message: 'Each entry must be a valid CIDR block.',
      },
    ],
    ui: {
      label: 'PrivateLink Subnet CIDRs',
      group: 'network',
      order: 3,
      inputType: 'cidr-list',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'isolated' }],
      helpText: 'CIDR blocks for PrivateLink subnets (one per availability zone, typically 3).',
      width: 'full',
    },
  },
  {
    name: 'sg_egress_ports',
    terraformType: 'list(string)',
    description: 'TCP egress ports for security group rules to VPC CIDR.',
    required: false,
    sensitive: false,
    default: [null],
    nullable: true,
    ui: {
      label: 'Security Group TCP Egress Ports',
      group: 'network',
      order: 4,
      inputType: 'list-editor',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'isolated' }],
      helpText: 'TCP ports allowed from workspace to VPC CIDR for Databricks services. Internode TCP/UDP communication (all ports, self-referencing) and S3 endpoint egress (TCP 443) are added automatically. Port 6666 is excluded in GovCloud.',
      width: 'full',
    },
  },
  {
    name: 'custom_vpc_id',
    terraformType: 'string',
    description: 'Custom VPC ID',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    ui: {
      label: 'Custom VPC ID',
      group: 'network',
      order: 5,
      inputType: 'text',
      placeholder: 'vpc-0123456789abcdef0',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'custom' }],
      helpText: 'The ID of your existing VPC.',
      width: 'half',
    },
  },
  {
    name: 'custom_private_subnet_ids',
    terraformType: 'list(string)',
    description: 'List of custom private subnet IDs',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    ui: {
      label: 'Custom Private Subnet IDs',
      group: 'network',
      order: 6,
      inputType: 'list-editor',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'custom' }],
      helpText: 'List of existing private subnet IDs to use for the Databricks workspace.',
      width: 'full',
    },
  },
  {
    name: 'custom_sg_id',
    terraformType: 'string',
    description: 'Custom security group ID',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    ui: {
      label: 'Custom Security Group ID',
      group: 'network',
      order: 7,
      inputType: 'text',
      placeholder: 'sg-0123456789abcdef0',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'custom' }],
      helpText: 'The ID of your existing security group.',
      width: 'half',
    },
  },
  {
    name: 'custom_relay_vpce_id',
    terraformType: 'string',
    description: 'Custom Relay VPC Endpoint ID',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    ui: {
      label: 'Custom Relay VPC Endpoint ID',
      group: 'network',
      order: 8,
      inputType: 'text',
      placeholder: 'vpce-0123456789abcdef0',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'custom' }],
      helpText: 'The VPC Endpoint ID for Secure Cluster Connectivity relay.',
      width: 'half',
    },
  },
  {
    name: 'custom_workspace_vpce_id',
    terraformType: 'string',
    description: 'Custom Workspace VPC Endpoint ID',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    ui: {
      label: 'Custom Workspace VPC Endpoint ID',
      group: 'network',
      order: 9,
      inputType: 'text',
      placeholder: 'vpce-0123456789abcdef0',
      visibleWhen: [{ field: 'network_configuration', operator: 'eq', value: 'custom' }],
      helpText: 'The VPC Endpoint ID for the Databricks workspace API.',
      width: 'half',
    },
  },

  // ── Security group ──────────────────────────────────────────────────────────
  {
    name: 'cmk_admin_arn',
    terraformType: 'string',
    description: 'Amazon Resource Name (ARN) of the CMK admin.',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    ui: {
      label: 'CMK Admin ARN',
      group: 'security',
      order: 1,
      inputType: 'text',
      placeholder: 'arn:aws:iam::123456789012:role/my-cmk-admin',
      helpText: 'ARN of the IAM principal that will administer the Customer Managed Key. If not set, the deploying principal is used.',
      width: 'full',
    },
  },

  // ── Advanced group ──────────────────────────────────────────────────────────
  {
    name: 'metastore_exists',
    terraformType: 'bool',
    description: 'If a metastore exists',
    required: true,
    sensitive: false,
    nullable: false,
    ui: {
      label: 'Metastore Already Exists',
      group: 'advanced',
      order: 1,
      inputType: 'checkbox',
      helpText: 'Whether a Unity Catalog metastore already exists in this region. If false, SRA will create one.',
      width: 'half',
    },
  },
  {
    name: 'audit_log_delivery_exists',
    terraformType: 'bool',
    description: 'If audit log delivery is already configured',
    required: false,
    sensitive: false,
    default: false,
    nullable: false,
    ui: {
      label: 'Audit Log Delivery Exists',
      group: 'advanced',
      order: 2,
      inputType: 'checkbox',
      helpText: 'Whether audit log delivery is already configured for this account. Audit log delivery can only be configured twice per account.',
      width: 'half',
    },
  },
  {
    name: 'enable_security_analysis_tool',
    terraformType: 'bool',
    description: 'Flag to enable the security analysis tool.',
    required: false,
    sensitive: true,
    default: false,
    nullable: false,
    ui: {
      label: 'Enable Security Analysis Tool',
      group: 'advanced',
      order: 3,
      inputType: 'checkbox',
      helpText: 'Enable the Security Analysis Tool (SAT) for continuous security monitoring. Deployed via Databricks Asset Bundles.',
      width: 'half',
    },
  },
  {
    name: 'enable_compliance_security_profile',
    terraformType: 'bool',
    description: 'Flag to enable the compliance security profile.',
    required: false,
    sensitive: true,
    default: false,
    nullable: false,
    ui: {
      label: 'Enable Compliance Security Profile',
      group: 'advanced',
      order: 4,
      inputType: 'checkbox',
      helpText: 'Enable the Compliance Security Profile (CSP) for the workspace. Standards must be specified in compliance_standards.',
      width: 'half',
    },
  },
  {
    name: 'compliance_standards',
    terraformType: 'list(string)',
    description: 'List of compliance standards.',
    required: false,
    sensitive: false,
    nullable: true,
    ui: {
      label: 'Compliance Standards',
      group: 'advanced',
      order: 5,
      inputType: 'list-editor',
      helpText: 'List of compliance standards to apply (e.g. HIPAA, PCI-DSS, FedRAMP).',
      width: 'full',
    },
  },
  {
    name: 'deployment_name',
    terraformType: 'string',
    description: 'Deployment name for the workspace. Must first be enabled by a Databricks representative.',
    required: false,
    sensitive: false,
    default: null,
    nullable: true,
    ui: {
      label: 'Deployment Name',
      group: 'advanced',
      order: 6,
      inputType: 'text',
      placeholder: 'my-deployment',
      helpText: 'Custom deployment name for the workspace URL. Must be pre-approved by a Databricks representative.',
      width: 'half',
    },
  },
];

// ─── Full provider schema ───────────────────────────────────────────────────

export const awsSchema: ProviderSchema = {
  provider: 'aws',
  displayName: 'Amazon Web Services',
  description: 'Deploy Databricks on AWS with VPC, PrivateLink, and security hardening',
  deploymentModes: awsDeploymentModes,
  variables: awsVariables,
};
